# Generated by Django 6.0.3 on 2026-03-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('safety', 'Safety'), ('waste', 'Waste'), ('water', 'Water'), ('air', 'Air'), ('lost', 'Lost')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('urgency', models.CharField(default='Medium', max_length=20)),
                ('description', models.TextField()),
                ('evidence', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
