# Generated by Django 6.0.3 on 2026-04-01 16:19

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='evidence',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='reports/'),
        ),
    ]
